### ISSUE TITLE
VRAM?

### ISSUE THREAD

**Issue by ShortyLegs** [jhj0517/Whisper-WebUI#11]
venv "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\\venv\Scripts\Python.exe"

Initializing Model..

Traceback (most recent call last):
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\app.py", line 24, in <module>
    whisper_inf = WhisperInference()
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\modules\whisper_Inference.py", line 15, in __init__
    self.model = whisper.load_model(name=DEFAULT_MODEL_SIZE, download_root="models/Whisper")
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\whisper\__init__.py", line 122, in load_model
    return model.to(device)
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\pc\Downloads\Compressed\Whisper-WebUI-master\Whisper-WebUI-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.00 GiB already allocated; 0 bytes free; 7.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Would I have to manually configure the use of another model? Maybe medium? Or is there another solution?

**Comment by Elvis143BRA** [comment]
It always downloads the large model, which requires 10 GB of VRAM. I haven't figured out how to make it installa a smaller model.

**Comment by jhj0517** [comment]
Hi, I've fixed this issue by setting the default model to None, in [5845bfc](https://github.com/jhj0517/Whisper-WebUI/commit/5845bfc543ad1bb82131d3b8532f1eb83140e3ea).
So I'm closing this issue, but If you face same issue again, please re-open it.
