### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xxetest** [jhj0517/Whisper-WebUI#114]
**Which OS are you using?**
 - OS: Kali Linux
 - NVIDIA P40 GPU with drivers installed

![图片](https://github.com/jhj0517/Whisper-WebUI/assets/110442766/d6edb121-3f4d-4a2a-93a8-1ee80d95ed07)

Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory. But it is at `home/a/Downloads/Whisper-WebUI/venv/lib/python3.11/site-packages/torch/lib/libcudnn_ops_infer.so.8`
The model is loaded, but then the error occurs and the model unloads:
![图片](https://github.com/jhj0517/Whisper-WebUI/assets/110442766/7b5b30eb-7058-45a8-a4d2-c6d2fd1001c8)

I've tried `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/a/Downloads/Whisper-WebUI/venv/lib/python3.11/site-packages/torch/lib` with no luck.

**Comment by xxetest** [comment]
First get into venv then add the .so to path worked.
![图片](https://github.com/jhj0517/Whisper-WebUI/assets/110442766/58cfc1f2-111a-4593-9f9e-d7c4ee6f22f3)

**Comment by fernvenue** [comment]
Hi, as `export` is not permanent, so I wanna share my setup. First, find `libcudnn_ops_infer.so.8`:

```
find / -name libcudnn_ops_infer.so.8
```

For example, my `libcudnn_ops_infer.so.8` is in `/etc/whisper/venv/lib/python3.11/site-packages/nvidia/cudnn/lib`, so I added this environment value to the systemd service file:

```
[Unit]
Description=Whisper
Documentation=https://github.com/jhj0517/Whisper-WebUI
After=network.target

[Service]
Type=simple
ExecStart=/etc/whisper/venv/bin/python3 /etc/whisper/app.py --server_name 0.0.0.0
Environment="LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/etc/whisper/venv/lib/python3.11/site-packages/nvidia/cudnn/lib"
WorkingDirectory=/etc/whisper
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

Now it works perfectly fine :)

**Comment by jhj0517** [comment]
duplicate with #271, if anyone faced the same error refer to https://github.com/jhj0517/Whisper-WebUI/issues/271#issuecomment-2350820352
