### ISSUE TITLE
{libcudnn_ops.so.9.1.0 

### ISSUE THREAD

**Issue by joelhoty** [jhj0517/Whisper-WebUI#346]
While transcribing YouTube video subtitles in Google Colab, the following error occurred:

Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor

**Comment by jhj0517** [comment]
Hi. This is fixed in #348.

The [new notebook](https://colab.research.google.com/github/jhj0517/Whisper-WebUI/blob/master/notebook/whisper-webui.ipynb) worked fine.

**Comment by jhj0517** [comment]
I'm closing assuming this is resolved, 
Feel free to reopen it!

**Comment by IbrahimOzmen** [comment]
I also have the same problem. i am trying to fine tune the xtts model with a gradio web gui. I dont know my problem is related to ctranslate2 but it is the exact same thing: 
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor

**Comment by jhj0517** [comment]
@IbrahimOzmen I'm guessing that some of your packages require their own cuDNN builds and are incompatible with the CUDA version installed in your environment (specific cuDNN version comes with specific CUDA version).

So my suggestion is to find the package that uses the dependent cuDNN and adjust that package's version to be compatible with your CUDA version.

**Comment by bmilde** [comment]
Installing the libcudnn9-cuda-12 package on ubuntu solved the issue for me:

`sudo apt-get install libcudnn9-cuda-12`

**Comment by paul-lupu** [comment]
> Installing the libcudnn9-cuda-12 package on ubuntu solved the issue for me:
> 
> `sudo apt-get install libcudnn9-cuda-12`

This worked for me as well on ubuntu. Thanks for sharing!
